- ansible/asqatasun/templates/asqatasun.cnf.j2
@mfaure @jkowalczyk @asqabotc3p0 @dzc34 we'll procced with this PR as I have closed the other PR:
- https://github.com/Asqatasun/Asqatasun/pull/44
- https://github.com/Asqatasun/Asqatasun/pull/46
- https://github.com/Asqatasun/Asqatasun/pull/45
> add cnf file as jinja2 template

- docker/single-container/Dockerfile
replace http://download.asqatasun.org/
by https://github.com/Asqatasun/Asqatasun/releases/download/
> docker/single-container : update download URL

- docker/compile_and_build_docker_image.sh
- add  options 	
- `--use-sudo-docker `
- `-p | --port `
- `-n | --container-name `
- `-i | --image-name `
- `-t | --tag-name `
- `-l | --only-localhost`
-  test if port is already allocated…
-  test if URL responds with 200
@mfaure can you review these commits ?
example: 
- `./(...).sh -s <path> -d <path> `
- `./(...).sh -s <path> -d <path> --use-sudo-docker`
- `./(...).sh -s <path> -d <path> -p 8086`
- `./(...).sh -s <path> -d <path> -p 8087 --only-localhost`
- `./(...).sh -s <path> -d <path> -p 8087 -l  -i local/asqa -t test1 -n asqa_test1`
> compile_and_build_docker_image.sh : add options + test if URL responds with 200

- runner/asqatasun-runner/src/main/resources/descriptor.xml
- web-app/asqatasun-web-app/src/main/resources/descriptor.xml
don't include  the .psql files for PostgreSQL into the tar.gz
> include the .psql files for PostgreSQL into the tar.gz
> only if all .psql files are available (RGAA3.0 and SEO do not exist)
> and a docker image is available for testing Asqatasun with PostgreSQL
@jkowalczyk @mfaure could you review this PR?
if it's is Ok for you, I myself manage the merge.
> tar.gz - deleted <include>*.psql</include> in descriptor.xml files

- documentation/en/90_Rules/rgaa3.2016/08.Mandatory_elements/Rule-8-10-2.md
- rules/rules-commons/src/main/java/org/asqatasun/rules/keystore/CssLikeQueryStore.java
- rules/rules-rgaa3.2016/src/main/java/org/asqatasun/rules/rgaa32016/Rgaa32016Rule081002.java
- rules/rules-rgaa3.2016/src/main/resources/sql/rgaa3.2016-insert.sql
- rules/rules-rgaa3.2016/src/test/java/org/asqatasun/rules/rgaa32016/Rgaa32016Rule081002Test.java
- rules/rules-rgaa3.2016/src/test/resources/testcases/rgaa32016/Rgaa32016Rule081002/Rgaa32016.Test.8.10.2-3NMI-01.html
- rules/rules-rgaa3.2016/src/test/resources/testcases/rgaa32016/Rgaa32016Rule081002/Rgaa32016.Test.8.10.2-4NA-01.html
Implementation of the rule 8.10.2 of the referential RGAA 3.2016
@jkowalczyk @mfaure could you review this PR (implementation and English) ?
if it's is Ok for you, I myself manage the merge.
an update is provided to supplement the rule by checking that the value of the dir attribute is valid (rtl or ltr)
> Rgaa 3.2016 8.10.2

- web-app/asqatasun-web-app/src/main/webapp/WEB-INF/view/failed-test-list.jsp
- web-app/asqatasun-web-app/src/main/webapp/WEB-INF/view/synthesis-site.jsp
> fix #179 - Site-audit in error: fix robots.txt URL

- web-app/asqatasun-web-app/src/main/webapp/.well-known/security.txt
- web-app/asqatasun-web-app/src/main/webapp/contribute.json
- web-app/asqatasun-web-app/src/main/webapp/robots.txt
- #190 Webapp - Added .well-known/security.txt
- #191 Webapp - Add contribute.json file
- #192 Webapp - Add robots.txt file
> Webapp - Fixed #190 #191 #192

- pom.xml
Update markdown dependency in the pom.xml
pom.xml
mvn clean install
no
> Update dependency: markdown-page-generator-plugin #218

- pom.xml
Modification of the version of dependency-check-maven in the pom.xml
There is only one modification in the pom.xml so the review will be fast.
Try to "mvn install" in cmd to see if maven can build the project and "mvn dependency-check:aggregate"
I don't understand the question
issue #217 
It's not appropriate
> Fixed #127 - Upgraded owasp:dependency-check (3.1.2 instead of 3.1.1)

- CONTRIBUTING.md
Correcting typos.
CONTRIBUTING.md
> Minor orthographic changes to CONTRIBUTING.md

- web-app/asqatasun-web-app/src/main/webapp/WEB-INF/view/contract.jsp
- web-app/asqatasun-web-app/src/main/webapp/WEB-INF/view/home.jsp
- web-app/asqatasun-web-app/src/main/webapp/WEB-INF/view/page-list-xxx.jsp
- web-app/asqatasun-web-app/src/main/webapp/WEB-INF/view/template/synthesis.jsp
- web-app/tgol-resources/src/main/resources/conf/asqatasun.conf
Set grade as default render view without a updating of asqatasun.conf.
Same result for "displayGradeAsResult=true" or "# displayGradeAsResult=true"
#251
> Set grade as default render view without a updating of asqatasun.conf

- web-app/tgol-resources/pom.xml
> WIP tgol-resources: change default policy from exclude to include

- web-app/tgol-resources/pom.xml
> Fix wrong path of included resources in tgol-resources project

- web-app/tgol-resources/src/main/resources/installation/install.sh
> 281 XVFB not functional on Ubuntu 18.04

- CHANGELOG.md
- README.md
> Prepare v4.1.0-rc.2

- engine/asqatasun-resources/src/main/resources/release/bump_asqatasun.sh
> Make release script more reliable

- engine/asqatasun-api/pom.xml
- pom.xml
> Fix #289, #290, #291, #292

- web-app/tgol-resources/src/main/resources/installation/pre-requisites-SQL-ubuntu-1804.sh
Fix #311 + innodb_redo_log_size
> 311 max allowed packet is not taken into account

- documentation/en/10_Install_doc/Asqatasun/Pre-requisites.md
- web-app/tgol-resources/src/main/resources/sql-update/tgol-40-update-from-4.0.3-to-4.1.0.sql
> 313 document sql changes

- documentation/en/30_Contributor_doc/Release/Release_RC.md
- documentation/en/30_Contributor_doc/Release/Release_Stable.md
- engine/asqatasun-resources/src/main/resources/release/bump_asqatasun.sh
> 315 adjust release script to manage release branch

- .travis.yml
> FIX #317 Configure Travis deployment only on tags

- CHANGELOG.md
- README.md
- documentation/en/30_Contributor_doc/Release/Release_RC.md
- documentation/en/30_Contributor_doc/Release/Release_Stable.md
- documentation/en/50_Administrator_doc/Upgrading/README.md
- documentation/en/50_Administrator_doc/Upgrading/Upgrade_from_v4.0.3_to_v4.1.0.md
- documentation/en/SUMMARY.md
> DOC Prepare v4.1.0-rc.5

- CHANGELOG.md
- README.md
> DOC Fix #328

- CHANGELOG.md
- README.md
> DOC Fix #330

- documentation/en/10_Install_doc/Asqatasun/Apache_frontend.md
- documentation/en/10_Install_doc/Asqatasun/README.md
- documentation/en/10_Install_doc/Asqatasun/Web_analytics.md
- documentation/en/50_Administrator_doc/Upgrading/Upgrade_from_v4.0.3_to_v4.1.0.md
- documentation/en/SUMMARY.md
* Fix #339 
* Add Apache config to enhance scores add SSLLabs and ozilla Observatory
* Add how to configure web analytics
> DOC FIX #339 upgrade doc + enhance apache config + add web analytics

- engine/asqatasun-api/pom.xml
- pom.xml
> #333 -  v4.1 - Update pom.xml: allow build with java11

- pom.xml
Fixed #336 
same as #292 (not backported yet)
related to #291 jacoco java 11 support
> #336 - v4.1: update jacoco dependancy

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
> FIX #345 Update Pull Request + issue templates

- documentation/en/10_Install_doc/Asqatasun/Apache_frontend.md
Thank you **very** much for contributing to Asqatasun!
Fix #347
> FIX #347 Update install doc

- documentation/en/50_Administrator_doc/Upgrading/Upgrade_from_v4.0.3_to_v4.1.0.md
Thank you **very** much for contributing to Asqatasun!
--> fix #349
> FIX #349 Update links for SQL upgrade scripts

- documentation/en/30_Contributor_doc/README.md
- documentation/en/30_Contributor_doc/Rules/README.md
Thank you **very** much for contributing to Asqatasun!
Fix #360
> DOC Add details on how to build rules
